name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/checkout@v3
        with:
          node-version: 16
      - name: Install Dependency
        run: npm install
      - name: Run tests
        run: npm test
      - name: Deploy to Production
    continue-on-error: npm run
